apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: restaurant
spec:
  selector:
    app: inventory-service
  ports:
    - name: http
      port: 8002
      targetPort: 8002
