apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: tracing-default
  namespace: restaurant
spec:
  tracing:
    - providers:
        - name: jaeger
      randomSamplingPercentage: 100.0
