apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - serviceaccounts.yaml
  - configmap.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - redis/statefulset.yaml
  - redis/service.yaml
  - order-service/deployment.yaml
  - order-service/service.yaml
  - inventory-service/deployment.yaml
  - inventory-service/service.yaml
  - billing-service/deployment.yaml
  - billing-service/service.yaml
  - reservation-service/deployment.yaml
  - reservation-service/service.yaml
  - istio/gateway.yaml
  - istio/virtual-services.yaml
  - istio/destination-rules.yaml
  - istio/peer-authentication.yaml
  - istio/authorization-policies.yaml
  - istio/tracing.yaml
  - canary/order-service-v2.yaml
  - canary/virtual-service-canary.yaml
