apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
  namespace: restaurant
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service
  namespace: restaurant
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: billing-service
  namespace: restaurant
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reservation-service
  namespace: restaurant
